# SPDX-License-Identifier: Apache-2.0
"""Pydantic schema for the recommended-models registry.

Wire shape for ``src/vaner/setup/recommended/data.json``. The
registry is generated by ``scripts/refresh_recommended_models.py``;
this module is the single source of truth for what the JSON must
look like, both for the generator (write side) and the loader /
resolver / API endpoint (read side).
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

# A short list of intent slugs the resolver consumes. Mirrors (a
# subset of) WorkStyle from setup.enums; we don't import that
# directly because ``general`` / ``unsure`` collapse to ``mixed`` for
# routing purposes and the registry stores the routing-relevant set.
IntentLean = Literal[
    "coding",
    "writing",
    "research",
    "planning",
    "support",
    "learning",
    "mixed",
]

RankSource = Literal[
    "ollama-library",
    "huggingface-downloads",
    "lmsys-arena",
    "synthesis",  # fallback when multiple sources contribute to the rank
]


class RegistrySource(BaseModel):
    """Provenance for a single source the generator consulted."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(..., description="Source identifier, e.g. 'ollama-library'.")
    snapshot_at: datetime = Field(..., description="When the source was queried.")
    note: str | None = Field(
        default=None,
        description="Optional human-readable note (e.g. 'fallback to cached snapshot — primary unreachable').",
    )


class RecommendedModel(BaseModel):
    """A single registry entry — one model the resolver may pick."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    id: str = Field(..., description="Canonical id used internally (typically the Ollama tag).")
    family: str = Field(..., description="Vendor/family slug, e.g. 'qwen', 'llama', 'gemma'.")
    params_b: float = Field(..., gt=0.0, description="Parameter count in billions (e.g. 7.0, 32.0).")
    min_effective_gb_q4: float = Field(
        ...,
        gt=0.0,
        description="Minimum MemoryBudget.effective_gb_q4 this model fits in.",
    )
    intent_lean: tuple[IntentLean, ...] = Field(
        default=(),
        description="Work-style affinities; empty tuple means 'general-purpose'.",
    )
    ollama_id: str | None = Field(
        default=None,
        description="Ollama pull id (e.g. 'qwen3:32b-instruct-q4_K_M'). May be null if HF-only.",
    )
    huggingface_id: str | None = Field(
        default=None,
        description="Hugging Face repo id (e.g. 'Qwen/Qwen3-32B-Instruct-GGUF'). May be null.",
    )
    context_length: int = Field(..., gt=0, description="Maximum context the model supports.")
    popularity_rank: int = Field(..., gt=0, description="1 = most popular within the source.")
    rank_source: RankSource = Field(..., description="Which signal produced popularity_rank.")

    @field_validator("intent_lean", mode="before")
    @classmethod
    def _coerce_to_tuple(cls, v: object) -> tuple[IntentLean, ...]:
        if isinstance(v, list):
            return tuple(v)  # type: ignore[return-value]
        return v  # type: ignore[return-value]


class Registry(BaseModel):
    """The complete registry document loaded from ``data.json``."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    schema_version: int = Field(default=1, ge=1)
    generated_at: datetime
    generator: str = Field(
        ...,
        description="Identifier of the producing script + git sha, e.g. 'refresh_recommended_models.py@abc1234'.",
    )
    sources: tuple[RegistrySource, ...] = Field(default=())
    models: tuple[RecommendedModel, ...] = Field(default=())

    @field_validator("sources", "models", mode="before")
    @classmethod
    def _coerce_seq(cls, v: object) -> object:
        if isinstance(v, list):
            return tuple(v)
        return v


__all__ = [
    "IntentLean",
    "RankSource",
    "RecommendedModel",
    "Registry",
    "RegistrySource",
]
