name: Actionlint

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          persist-credentials: false
      - name: Run actionlint
        run: docker run --rm -v "$PWD:/repo" -w /repo rhysd/actionlint:1.7.7
      - name: Zizmor
        uses: zizmorcore/zizmor-action@814f9778aceea8641503a8cd8f0cffebc55d790c # v0.5.3
        with:
          inputs: .github/workflows
          online-audits: false
